### ISSUE TITLE
機關列表 / 數據整理

### ISSUE THREAD

**Issue by yutin1987** [opengovdatatw/dataopener#13]
資料來源 (需統計) https://docs.google.com/spreadsheets/d/14ceZCncQGpndd8hmJwX8SrhVBFFUl41st0XFeWmSWXE/edit#gid=561634746

**Comment by yutin1987** [comment]
by 機關整理出結果. 視覺可參考 https://github.com/opengovdatatw/dataopener/issues/14

**Comment by voidlps** [comment]
based on dataopener-flat.json authority, counts are ("要分案": 236 not included)
  "臺南市政府": 149,
  "高雄市政府": 120,
  "臺東縣政府": 77,
  "嘉義市政府": 78,
  "基隆市政府": 67,
  "屏東縣政府": 78,
  "南投縣政府": 30,
  "花蓮縣政府": 78,
  "澎湖縣政府": 76,
  "嘉義縣政府": 29,
  "金門縣政府": 30,
  "苗栗縣政府": 78,
  "雲林縣政府": 77,
  "桃園市政府": 85,
  "彰化縣政府": 75,
  "宜蘭縣政府": 72,
  "新北市政府": 35,
  "連江縣政府": 30,
  "臺中市政府": 82,
  "新竹縣政府": 27,
  "新竹市政府": 28,
  "臺北市政府": 116,
  "行政院主計總處": 20,
  "本平臺營運窗口": 146,
  "國家通訊傳播委員會": 10,
  "內政部": 175,
  "法務部": 22,
  "司法院": 18,
  "科技部": 11,
  "交通部": 156,
  "考選部": 6,
  "金融監督管理委員會": 56,
  "經濟部": 202,
  "勞動部": 34,
  "客家委員會": 2,
  "行政院環境保護署": 56,
  "衛生福利部": 107,
  "財政部": 51,
  "原住民族委員會": 8,
  "行政院農業委員會": 68,
  "台灣電力股份有限公司": 84,
  "文化部": 8,
  "國家發展委員會": 28,
  "教育部": 99,
  "外交部": 11,
  "行政院": 6,
  "國防部": 11,
  "僑務委員會": 3,
  "國軍退除役官兵輔導委員會": 3,
  "行政院原子能委員會": 19,
  "大陸委員會": 3,
  "國立故宮博物院": 2,
  "中央銀行": 2,
  "中央選舉委員會": 10,
  "公平交易委員會": 2,
  "行政院公共工程委員會": 12,
  "臺灣省諮議會": 2,
  "行政院人事行政總處": 14,
  "監察院": 2,
  "立法院": 6,
  "銓敘部": 3,
  "海洋委員會": 2,
  "經濟部能源局": 63,
  "交通部公路總局": 1,
  "總統府": 5,
  "內政部戶政司": 1,
  "主計處": 1,
  "行政院國家發展基金管理會": 1,
  "財政部統計處": 3,
  "內政部警政署": 2,
  "國家圖書館": 1

**Comment by yutin1987** [comment]
done
