### ISSUE TITLE
常見問答/申請後

### ISSUE THREAD

**Issue by shuchenchang** [opengovdatatw/dataopener#17]
申請後內容要上網 (目前只有申請前)
網頁位址 https://dataopener.tw/fnq
內容來源 https://hackmd.io/0mQqHviYSAqqnRl6Ai4aHA#%E7%94%B3%E8%AB%8B%E5%BE%8C

![image](https://user-images.githubusercontent.com/18047124/73425501-c478c700-436c-11ea-9d37-015d039ce935.png)

**Comment by yutin1987** [comment]
ok, in process

**Comment by yutin1987** [comment]
done
