### ISSUE TITLE
開放資料累積申請數

### ISSUE THREAD

**Issue by yutin1987** [opengovdatatw/dataopener#2]
<img width="1450" alt="螢幕快照 2020-01-17 下午1 19 11" src="https://user-images.githubusercontent.com/2505934/72586219-f9782900-392b-11ea-8cbd-b6d7af66bf92.png">

參考數據 https://docs.google.com/spreadsheets/d/14ceZCncQGpndd8hmJwX8SrhVBFFUl41st0XFeWmSWXE/edit#gid=561634746

**Comment by voidlps** [comment]
close for the feature is finished by **pull request** #20 &  97226b2c985302d238586be295c46067d6feb5c2
