### ISSUE TITLE
我要申請 / 複製表單內容加上alert (揪松建議)

### ISSUE THREAD

**Issue by shuchenchang** [opengovdatatw/dataopener#26]
「複製表單內容」按鈕是否可以加個 alert「已複製入剪貼簿」之類的，提醒使用者

**Comment by shuchenchang** [comment]
使用者按「複製表單內容，並前往資料申請！」
出現alert

已複製表單內容，全速前往申請中

然後直接連過去，這樣呢？

**Comment by yutin1987** [comment]
done
