### ISSUE TITLE
(揪松) 換頁後的 scroll position

### ISSUE THREAD

**Issue by voidlps** [opengovdatatw/dataopener#28]
資料搜尋的部分，我按下一頁有出現下一頁的資料，但頁面會停留在最下面，使用者要自己往上拉才看的到新資料

**HOW TO REPRODUCE**
1. open https://dataopener.tw/searcher
2. input "公司“
3. scroll to the bottom
4. click "2" to switch to page 2
* Current:
Data switched but scroll position is not changed
* Expected:
jump to the top of page 2 records

**Comment by yutin1987** [comment]
done
