### ISSUE TITLE
(揪松)分頁造成的資料更新問題

### ISSUE THREAD

**Issue by voidlps** [opengovdatatw/dataopener#30]
在搜尋 A 資料時，我瀏覽到下一頁，然後我換個主題搜尋 B 資料，會殘留 A 資料的結果

** HOW TO REPRODUCE **
1. open https://dataopener.tw/searcher
2. input "停車位“
3. scroll to button
4. click page 3
5. click page 1
6. input "農業“

* Current:
有一筆「停車位」資料會被留下。實際上應該是在第5步切回page 1時就有了，只是不容易注意到

* Expected
換頁或重新搜尋時，正確顯示結果

**Comment by yutin1987** [comment]
fixed
